// overlay: ceramic + chipboard/WPC finishes
window.F=window.F||[];
if(!F.some(x=>x[0]==='CR-501')) F.push(['CR-501','ceramic','سيراميك رخامي أبيض','Ceramic marble white','#f2f0ea']);
if(!F.some(x=>x[0]==='CR-502')) F.push(['CR-502','ceramic','سيراميك رخامي رمادي','Ceramic marble grey','#c5c8cb']);
if(!F.some(x=>x[0]==='CR-503')) F.push(['CR-503','ceramic','سيراميك رخامي بيج','Ceramic marble beige','#e0d2bc']);
if(!F.some(x=>x[0]==='CR-504')) F.push(['CR-504','ceramic','سيراميك رخامي أسود','Ceramic marble black','#2a2a2c']);
if(!F.some(x=>x[0]==='CR-505')) F.push(['CR-505','ceramic','سيراميك خشبي فاتح','Ceramic wood light','#d4c4a0']);
if(!F.some(x=>x[0]==='CR-506')) F.push(['CR-506','ceramic','سيراميك خشبي جوزي','Ceramic wood walnut','#6b4423']);
if(!F.some(x=>x[0]==='CR-507')) F.push(['CR-507','ceramic','سيراميك تيرازو','Ceramic terrazzo look','#d8d0c4']);
if(!F.some(x=>x[0]==='CR-508')) F.push(['CR-508','ceramic','سيراميك كونكريت','Ceramic concrete look','#9a9a96']);
if(!F.some(x=>x[0]==='CR-509')) F.push(['CR-509','ceramic','سيراميك مترو أبيض','Ceramic metro white','#f5f5f2']);
if(!F.some(x=>x[0]==='CR-510')) F.push(['CR-510','ceramic','سيراميك مترو رمادي','Ceramic metro grey','#a8acb0']);
if(!F.some(x=>x[0]==='CR-511')) F.push(['CR-511','ceramic','سيراميك فسيفساء','Ceramic mosaic look','#c8bba5']);
if(!F.some(x=>x[0]==='CR-512')) F.push(['CR-512','ceramic','سيراميك حجر رملي','Ceramic sandstone','#dcc9ae']);
if(!F.some(x=>x[0]==='CR-513')) F.push(['CR-513','ceramic','سيراميك جرانيت رمادي','Ceramic granite grey','#8a9096']);
if(!F.some(x=>x[0]==='CR-514')) F.push(['CR-514','ceramic','سيراميك جرانيت أسود','Ceramic granite black','#3e3e40']);
if(!F.some(x=>x[0]==='CR-515')) F.push(['CR-515','ceramic','سيراميك رخام ذهبي','Ceramic gold marble','#e6d4b4']);
if(!F.some(x=>x[0]==='CR-516')) F.push(['CR-516','ceramic','سيراميك أزرق رمادي','Ceramic blue-grey','#a8b4be']);
if(!F.some(x=>x[0]==='CR-517')) F.push(['CR-517','ceramic','سيراميك أخضر هادئ','Ceramic quiet green','#b5bfb0']);
if(!F.some(x=>x[0]==='CR-518')) F.push(['CR-518','ceramic','سيراميك وردي باهت','Ceramic soft pink','#e8d4d0']);
if(!F.some(x=>x[0]==='CR-519')) F.push(['CR-519','ceramic','سيراميك لامع أبيض','Ceramic gloss white','#fafafa']);
if(!F.some(x=>x[0]==='CR-520')) F.push(['CR-520','ceramic','سيراميك مطفي رمادي','Ceramic matte grey','#b0b4b8']);
if(!F.some(x=>x[0]==='CB-601')) F.push(['CB-601','chipboard','شيبورد بلوط فاتح','Chipboard light oak','#c4a574']);
if(!F.some(x=>x[0]==='CB-602')) F.push(['CB-602','chipboard','شيبورد بلوط طبيعي','Chipboard natural oak','#b8955e']);
if(!F.some(x=>x[0]==='CB-603')) F.push(['CB-603','chipboard','شيبورد جوزي','Chipboard walnut','#6b4423']);
if(!F.some(x=>x[0]==='CB-604')) F.push(['CB-604','chipboard','شيبورد رمادي دخاني','Chipboard smoke grey','#8a8278']);
if(!F.some(x=>x[0]==='CB-605')) F.push(['CB-605','chipboard','شيبورد كربوني','Chipboard carbon','#3a342e']);
if(!F.some(x=>x[0]==='CB-606')) F.push(['CB-606','chipboard','شيبورد أبيض مبيّض','Chipboard bleached','#e8e0d4']);
if(!F.some(x=>x[0]==='CB-607')) F.push(['CB-607','chipboard','شيبورد تيك','Chipboard teak','#a67c52']);
if(!F.some(x=>x[0]==='CB-608')) F.push(['CB-608','chipboard','شيبورد رملي','Chipboard sand','#cbb892']);
if(!F.some(x=>x[0]==='WP-701')) F.push(['WP-701','chipboard','WPC فلوت فاتح','WPC fluted light','#d4c4a0']);
if(!F.some(x=>x[0]==='WP-702')) F.push(['WP-702','chipboard','WPC فلوت طبيعي','WPC fluted natural','#b8955e']);
if(!F.some(x=>x[0]==='WP-703')) F.push(['WP-703','chipboard','WPC فلوت جوزي','WPC fluted walnut','#5c3a22']);
if(!F.some(x=>x[0]==='WP-704')) F.push(['WP-704','chipboard','WPC فلوت رمادي','WPC fluted grey','#9a958c']);
if(!F.some(x=>x[0]==='WP-705')) F.push(['WP-705','chipboard','WPC فلوت فحمي','WPC fluted charcoal','#2f2b28']);
if(!F.some(x=>x[0]==='WP-706')) F.push(['WP-706','chipboard','WPC فلوت عسلي','WPC fluted honey','#c9a66b']);
if(!F.some(x=>x[0]==='WP-707')) F.push(['WP-707','chipboard','WPC بامبو فاتح','WPC bamboo light','#d2b48c']);
if(!F.some(x=>x[0]==='WP-708')) F.push(['WP-708','chipboard','WPC بامبو داكن','WPC bamboo dark','#8b6914']);
if(!F.some(x=>x[0]==='WP-709')) F.push(['WP-709','chipboard','WPC شيبورد جداري','WPC wall chipboard look','#c9b18a']);
if(!F.some(x=>x[0]==='WP-710')) F.push(['WP-710','chipboard','WPC داخلي سادة','WPC interior solid look','#e6ddd0']);
(function(){
  if(!window.F||!F.length) return;
  if(F[0].length===4){
    F=F.map(function(x){
      var code=x[0], ar=x[1], en=x[2], col=x[3], fam='wood';
      if(/^M2|^L-/.test(code)) fam='textile';
      else if(/^M3|^MB-/.test(code)) fam='marble';
      else if(/^S-/.test(code)) fam='solid';
      else if(/^CR-/.test(code)) fam='ceramic';
      else if(/^(CB|WP)-/.test(code)) fam='chipboard';
      return [code,fam,ar,en,col];
    });
  }
  var fixes={'M2-001':['textile','كتان / قماش','Linen / textile','#d7cfc3'],'M3-001':['marble','رخام فاتح','Light marble','#ece7df'],'M3-002':['marble','رخام رمادي','Grey marble','#9aa0a6'],'M3-003':['marble','رخام معرّق','Veined marble','#d9d2c8']};
  F=F.map(function(x){ var f=fixes[x[0]]; return f?[x[0],f[0],f[1],f[2],f[3]]:x; });
})();
window.SH=window.SH||[];
if(!SH.some(x=>x[0]==='SH-431')) SH.push(['SH-431','بلاطة سيراميك مربعة','Ceramic square tile look','#f2f0ea']);
if(!SH.some(x=>x[0]==='SH-432')) SH.push(['SH-432','بلاطة سيراميك رخام','Ceramic marble square','#ebe8e2']);
if(!SH.some(x=>x[0]==='SH-433')) SH.push(['SH-433','بلاطة سيراميك خشب','Ceramic wood square','#c4a574']);
if(!SH.some(x=>x[0]==='SH-434')) SH.push(['SH-434','بلاطة سيراميك مترو','Ceramic metro square','#f5f5f2']);
if(!SH.some(x=>x[0]==='SH-435')) SH.push(['SH-435','بلاطة شيبورد مربعة','Chipboard square look','#d0c4b0']);
if(!SH.some(x=>x[0]==='SH-436')) SH.push(['SH-436','لوح شيبورد 122','Chipboard 122 sheet','#c9b18a']);
if(!SH.some(x=>x[0]==='SH-437')) SH.push(['SH-437','لوح WPC 122','WPC 122 sheet','#b8955e']);
if(!SH.some(x=>x[0]==='SH-438')) SH.push(['SH-438','بلاطة WPC فلوت','WPC fluted square','#a8885a']);
if(!SH.some(x=>x[0]==='SH-439')) SH.push(['SH-439','مربع رخام كبير','Large marble square','#efeae2']);
if(!SH.some(x=>x[0]==='SH-440')) SH.push(['SH-440','مربع خشب متعرج','Herringbone wood square','#b8955e']);
if(!SH.some(x=>x[0]==='SH-441')) SH.push(['SH-441','مربع تيرازو سيراميك','Terrazzo ceramic square','#d8d0c4']);
if(!SH.some(x=>x[0]==='SH-442')) SH.push(['SH-442','مربع كونكريت سيراميك','Concrete ceramic square','#9a9a96']);
if(!SH.some(x=>x[0]==='SH-443')) SH.push(['SH-443','لوح بديل سيراميك 122','Ceramic-look 122 sheet','#e8e2d8']);
if(!SH.some(x=>x[0]==='SH-444')) SH.push(['SH-444','لوح بديل رخام لامع','Gloss marble-look sheet','#f0ebe3']);
if(!SH.some(x=>x[0]==='SH-445')) SH.push(['SH-445','شيبورد سادة كريمي','Cream chipboard sheet','#efe6d5']);
