// Additional finishes available to order — no photo, no price, no ISO claim.
(function(){
  if (typeof F==="undefined") return;
  var more=[
    ['W-041','wood','بلوط فاتح هادئ — للطلب','Quiet light oak — to order','#d8c4a2'],
    ['W-042','wood','بلوط عسلي — للطلب','Honey oak — to order','#c49a62'],
    ['W-043','wood','بلوط مدخن — للطلب','Smoked oak — to order','#8d7b68'],
    ['W-044','wood','بلوط أبيض مغسول — للطلب','Whitewashed oak — to order','#e6ded2'],
    ['W-045','wood','جوز أمريكي دافئ — للطلب','Warm American walnut — to order','#6b4428'],
    ['W-046','wood','جوز أوروبي — للطلب','European walnut — to order','#5c3a24'],
    ['W-047','wood','تيك ذهبي — للطلب','Golden teak — to order','#b88848'],
    ['W-048','wood','تيك غامق — للطلب','Dark teak — to order','#6e4a2a'],
    ['W-049','wood','زان فاتح — للطلب','Light beech — to order','#e2c9a4'],
    ['W-050','wood','زان طبيعي — للطلب','Natural beech — to order','#c9a36a'],
    ['W-051','wood','قيقب هادئ — للطلب','Quiet maple — to order','#e6d3b0'],
    ['W-052','wood','قيقب عسلي — للطلب','Honey maple — to order','#d4b483'],
    ['W-053','wood','كرز دافئ — للطلب','Warm cherry — to order','#8d4b38'],
    ['W-054','wood','كرز متوسط — للطلب','Medium cherry — to order','#7a3e30'],
    ['W-055','wood','ماهوجني ناعم — للطلب','Soft mahogany — to order','#6a3328'],
    ['W-056','wood','ماهوجني غامق — للطلب','Dark mahogany — to order','#4e261e'],
    ['W-057','wood','رماد فاتح — للطلب','Light ash — to order','#d9d0c2'],
    ['W-058','wood','رماد رمادي — للطلب','Grey ash — to order','#a39b92'],
    ['W-059','wood','دردار طبيعي — للطلب','Natural elm — to order','#b08a5a'],
    ['W-060','wood','صنوبر عقدي فاتح — للطلب','Light knotted pine — to order','#e0c89a'],
    ['W-061','wood','صنوبر عسلي — للطلب','Honey pine — to order','#c9a46a'],
    ['W-062','wood','أوكاليبتوس رمادي — للطلب','Grey eucalyptus — to order','#9a9288'],
    ['W-063','wood','بلوط ريفي — للطلب','Rustic oak — to order','#a88458'],
    ['W-064','wood','خشب زيتوني دافئ — للطلب','Warm olive wood — to order','#8a7a48'],
    ['W-065','wood','خشب فحمي ناعم — للطلب','Soft charcoal wood — to order','#3a342e'],
    ['W-066','wood','خشب رملي دافئ — للطلب','Warm sand wood — to order','#cbb892'],
    ['W-067','wood','خشب كريمي — للطلب','Cream wood — to order','#e8dcc8'],
    ['W-068','wood','خشب بندقي — للطلب','Hazelnut wood — to order','#a67c52'],
    ['W-069','wood','خشب قهوة — للطلب','Coffee wood — to order','#5a4034'],
    ['W-070','wood','خشب شوكولاتة — للطلب','Chocolate wood — to order','#4a3228'],
    ['W-071','wood','خشب لؤلؤي — للطلب','Pearl wood — to order','#ddd4c8'],
    ['W-072','wood','خشب دخاني فاتح — للطلب','Light smoke wood — to order','#b7aea4'],
    ['W-073','wood','خشب أبنوس ناعم — للطلب','Soft ebony look — to order','#2c2826'],
    ['W-074','wood','خشب جوز هند — للطلب','Coconut wood look — to order','#6e5844'],
    ['W-075','wood','خشب خيزران فاتح — للطلب','Light bamboo look — to order','#d8c49a'],
    ['W-076','wood','خشب متعرج هادئ — للطلب','Quiet herringbone wood — to order','#b8955e'],
    ['W-077','wood','فلوت بلوط — للطلب','Fluted oak — to order','#c4a574'],
    ['W-078','wood','فلوت جوز — للطلب','Fluted walnut — to order','#6b4428'],
    ['W-079','wood','فلوت رمادي — للطلب','Fluted grey wood — to order','#8a8278'],
    ['W-080','wood','فلوت أبيض — للطلب','Fluted white wood — to order','#e8e2d8'],
    ['MB-131','marble','رخام كريمي ناعم — للطلب','Soft cream marble — to order','#f3eadf'],
    ['MB-132','marble','رخام عاجي — للطلب','Ivory marble — to order','#f6f1e8'],
    ['MB-133','marble','كالاكاتا ذهبي خفيف — للطلب','Light gold Calacatta — to order','#f3ead8'],
    ['MB-134','marble','كالاكاتا رمادي — للطلب','Grey Calacatta — to order','#e7e4df'],
    ['MB-135','marble','كارارا ناعم — للطلب','Soft Carrara — to order','#f0eeea'],
    ['MB-136','marble','رخام بيج دافئ بلس — للطلب','Warm beige marble plus — to order','#e0ccb0'],
    ['MB-137','marble','رخام رملي — للطلب','Sand marble — to order','#e6d5bc'],
    ['MB-138','marble','رخام عرق فضي — للطلب','Silver vein marble — to order','#d5d8dc'],
    ['MB-139','marble','رخام عرق ذهبي — للطلب','Gold vein marble — to order','#e7d3b0'],
    ['MB-140','marble','رخام نيرو ناعم — للطلب','Soft nero marble — to order','#2e2e30'],
    ['MB-141','marble','رخام إمبيردور فاتح — للطلب','Light emperador — to order','#cbb79a'],
    ['MB-142','marble','رخام إمبيردور غامق — للطلب','Dark emperador — to order','#8c7356'],
    ['MB-143','marble','ترافرتين كريمي — للطلب','Cream travertine look — to order','#e6d5bc'],
    ['MB-144','marble','ترافرتين بيج — للطلب','Beige travertine look — to order','#d8c4a6'],
    ['MB-145','marble','رخام أخضر هادئ بلس — للطلب','Quiet green marble plus — to order','#b7c2b4'],
    ['MB-146','marble','رخام روز ناعم — للطلب','Soft rose marble — to order','#e8d5d0'],
    ['MB-147','marble','رخام توب — للطلب','Taupe marble — to order','#c8beb2'],
    ['MB-148','marble','رخام أبيض مطفي — للطلب','Matte white marble — to order','#f4f2ee'],
    ['MB-149','marble','رخام لامع كريمي — للطلب','Gloss cream marble — to order','#f7f0e4'],
    ['MB-150','marble','رخام رمادي غامق — للطلب','Dark grey marble — to order','#6e7276'],
    ['MB-151','marble','رخام سحابي — للطلب','Cloud marble — to order','#e4e7ea'],
    ['MB-152','marble','رخام صدفي — للطلب','Shell marble — to order','#eee6dc'],
    ['MB-153','marble','رخام عرق أسود رفيع — للطلب','Fine black vein — to order','#eceae6'],
    ['MB-154','marble','رخام بورتورو ناعم — للطلب','Soft Portoro look — to order','#3a3834'],
    ['MB-155','marble','رخام ذهبي هادئ — للطلب','Quiet gold marble — to order','#e6d2ae'],
    ['MB-156','marble','رخام زيتوني حجر — للطلب','Olive stone marble — to order','#9aa48a'],
    ['MB-157','marble','رخام أزرق رمادي هادئ — للطلب','Quiet blue-grey marble — to order','#c5ced6'],
    ['MB-158','marble','رخام أبيض عرق بني — للطلب','White brown-vein marble — to order','#f2ebe3'],
    ['MB-159','marble','رخام بيج عرق — للطلب','Veined beige marble — to order','#e4d4be'],
    ['MB-160','marble','رخام حمام فاتح — للطلب','Light bath marble look — to order','#f5f2ec'],
    ['MB-161','marble','رخام مطبخ رمادي — للطلب','Kitchen grey marble — to order','#c5c8cb'],
    ['MB-162','marble','رخام استقبال أبيض — للطلب','Reception white marble — to order','#f7f5f1'],
    ['MB-163','marble','رخام عمود كريمي — للطلب','Column cream marble — to order','#efe4d4'],
    ['MB-164','marble','رخام كونتر ناعم — للطلب','Soft counter marble look — to order','#e8e0d6'],
    ['MB-165','marble','رخام كتاب مفتوح — للطلب','Bookmatch marble look — to order','#f0ebe4'],
    ['MB-166','marble','رخام ميكرو عرق — للطلب','Micro-vein marble — to order','#e9e4dc'],
    ['MB-167','marble','رخام دافئ متوسط — للطلب','Medium warm marble — to order','#d9c6ae'],
    ['MB-168','marble','رخام بارد فاتح — للطلب','Cool light marble — to order','#e7eaec'],
    ['MB-169','marble','رخام كشمير — للطلب','Cashmere marble — to order','#e3d5c4'],
    ['MB-170','marble','رخام صحراوي — للطلب','Desert marble — to order','#d8c3a0'],
    ['L-221','textile','كتان طبيعي — للطلب','Natural linen — to order','#e4d8c8'],
    ['L-222','textile','كتان رملي — للطلب','Sand linen — to order','#d8c8b0'],
    ['L-223','textile','كتان رمادي — للطلب','Grey linen — to order','#c8c4bc'],
    ['L-224','textile','كتان كريمي — للطلب','Cream linen — to order','#f0e6d6'],
    ['L-225','textile','كتان بيج — للطلب','Beige linen — to order','#e0d0b8'],
    ['L-226','textile','كتان زيتي — للطلب','Olive linen — to order','#b3ae96'],
    ['L-227','textile','كتان توب — للطلب','Taupe linen — to order','#c4b8a8'],
    ['L-228','textile','كتان أبيض دافئ — للطلب','Warm white linen — to order','#f4efe8'],
    ['L-229','textile','كتان فحمي ناعم — للطلب','Soft charcoal linen — to order','#6a6662'],
    ['L-230','textile','قماش قطني فاتح — للطلب','Light cotton cloth — to order','#efe6da'],
    ['L-231','textile','قماش شانتونج — للطلب','Shantung look — to order','#e6dcc8'],
    ['L-232','textile','قماش صوف ناعم — للطلب','Soft wool look — to order','#d5cbbd'],
    ['L-233','textile','قماش بوكليه هادئ — للطلب','Quiet boucle look — to order','#ddd4c8'],
    ['L-234','textile','قماش مخمل مطفي — للطلب','Matte velvet look — to order','#8d735c'],
    ['L-235','textile','كتان مخطط ناعم — للطلب','Fine striped linen — to order','#d9d0c4'],
    ['L-236','textile','كتان غرفة نوم — للطلب','Bedroom linen — to order','#e8dfd2'],
    ['L-237','textile','كتان مكتب هادئ — للطلب','Quiet office linen — to order','#d4cfc6'],
    ['L-238','textile','كتان كافيه — للطلب','Café linen — to order','#c9b89a'],
    ['L-239','textile','كتان عيادة — للطلب','Clinic linen — to order','#e7e2da'],
    ['L-240','textile','كتان فندق — للطلب','Hotel linen — to order','#ddd2c2'],
    ['L-241','textile','قماش جوت فاتح — للطلب','Light jute look — to order','#cbb892'],
    ['L-242','textile','قماش جوت طبيعي — للطلب','Natural jute look — to order','#b89a6a'],
    ['L-243','textile','كتان وردي ترابي — للطلب','Earthy blush linen — to order','#e4d0c6'],
    ['L-244','textile','كتان أزرق رمادي — للطلب','Blue-grey linen — to order','#c5cdd2'],
    ['L-245','textile','كتان أخضر مريمية — للطلب','Sage linen — to order','#c5cbb8'],
    ['L-246','textile','قماش تويد ناعم — للطلب','Soft tweed look — to order','#b7aa96'],
    ['L-247','textile','كتان مضلع خفيف — للطلب','Light ribbed linen — to order','#e0d6c8'],
    ['L-248','textile','كتان حائط مميز — للطلب','Feature-wall linen — to order','#d8c4a6'],
    ['L-249','textile','كتان استقبال — للطلب','Reception linen — to order','#e6ddd0'],
    ['L-250','textile','كتان صالون — للطلب','Salon linen — to order','#f0e4d8'],
    ['L-251','textile','قماش كتان خام — للطلب','Raw linen cloth — to order','#d2c4ae'],
    ['L-252','textile','كتان دافئ متوسط — للطلب','Medium warm linen — to order','#c9b496'],
    ['L-253','textile','كتان فاتح جداً — للطلب','Very light linen — to order','#f6f1ea'],
    ['L-254','textile','كتان بني هادئ — للطلب','Quiet brown linen — to order','#a89078'],
    ['L-255','textile','كتان حجري — للطلب','Stone linen — to order','#cfc6ba'],
    ['S-313','solid','ساده كريمي — للطلب','Cream solid — to order','#f3eadc'],
    ['S-314','solid','ساده عاجي — للطلب','Ivory solid — to order','#f7f3ec'],
    ['S-315','solid','ساده أبيض دافئ — للطلب','Warm white solid — to order','#f4f1ec'],
    ['S-316','solid','ساده أبيض بارد — للطلب','Cool white solid — to order','#f2f4f5'],
    ['S-317','solid','ساده رملي — للطلب','Sand solid — to order','#e4d5bc'],
    ['S-318','solid','ساده بيج — للطلب','Beige solid — to order','#e0d0b8'],
    ['S-319','solid','ساده توب — للطلب','Taupe solid — to order','#c8beb4'],
    ['S-320','solid','ساده رمادي فاتح — للطلب','Light grey solid — to order','#d5d7d8'],
    ['S-321','solid','ساده رمادي متوسط — للطلب','Medium grey solid — to order','#b7bbbe'],
    ['S-322','solid','ساده رمادي غامق — للطلب','Dark grey solid — to order','#6e7276'],
    ['S-323','solid','ساده فحمي — للطلب','Charcoal solid — to order','#3e4044'],
    ['S-324','solid','ساده أسود ناعم — للطلب','Soft black solid — to order','#2a2a2c'],
    ['S-325','solid','ساده أخضر مريمية — للطلب','Sage solid — to order','#b7c0b0'],
    ['S-326','solid','ساده أخضر زيتوني — للطلب','Olive solid — to order','#8d9274'],
    ['S-327','solid','ساده أزرق رمادي — للطلب','Blue-grey solid — to order','#b7c2cc'],
    ['S-328','solid','ساده أصفر ترابي خفيف — للطلب','Light clay solid — to order','#e2c8a4'],
    ['S-329','solid','ساده بني فاتح — للطلب','Light brown solid — to order','#c4a882'],
    ['S-330','solid','ساده بني قهوة — للطلب','Coffee solid — to order','#6a5040'],
    ['S-331','solid','ساده وردي ترابي — للطلب','Earthy blush solid — to order','#e6d0c8'],
    ['S-332','solid','ساده ذهبي مطفي — للطلب','Matte gold solid — to order','#d8c49a'],
    ['S-333','solid','ساده فضي مطفي — للطلب','Matte silver solid — to order','#d5d8dc'],
    ['S-334','solid','ساده عيادات — للطلب','Clinic solid — to order','#f2f4f3'],
    ['S-335','solid','ساده مكاتب — للطلب','Office solid — to order','#d8d4ce'],
    ['S-336','solid','ساده مطابخ — للطلب','Kitchen solid — to order','#f0e8dc'],
    ['S-337','solid','ساده حمامات — للطلب','Bath solid — to order','#e8eeea'],
    ['S-338','solid','ساده مول — للطلب','Mall solid — to order','#e6e2dc'],
    ['S-339','solid','ساده كافيه — للطلب','Café solid — to order','#d8c4a8'],
    ['S-340','solid','ساده فندق — للطلب','Hotel solid — to order','#e4d8c8'],
    ['S-341','solid','ساده أطفال هادئ — للطلب','Quiet kids solid — to order','#f6efe4'],
    ['S-342','solid','ساده استقبال — للطلب','Reception solid — to order','#efe8de'],
    ['CR-521','ceramic','سيراميك أبيض مترو — للطلب','White metro ceramic look — to order','#f5f5f2'],
    ['CR-522','ceramic','سيراميك كريمي مترو — للطلب','Cream metro ceramic — to order','#f3eadc'],
    ['CR-523','ceramic','سيراميك رمادي مترو — للطلب','Grey metro ceramic — to order','#d5d7d8'],
    ['CR-524','ceramic','سيراميك أسود مترو — للطلب','Black metro ceramic — to order','#2e2e30'],
    ['CR-525','ceramic','سيراميك مربعات بيضاء — للطلب','White square ceramic — to order','#f7f6f3'],
    ['CR-526','ceramic','سيراميك مربعات بيج — للطلب','Beige square ceramic — to order','#e6d8c4'],
    ['CR-527','ceramic','سيراميك مربعات رمادية — للطلب','Grey square ceramic — to order','#c8cccf'],
    ['CR-528','ceramic','سيراميك خشب مربع — للطلب','Wood-square ceramic — to order','#c4a574'],
    ['CR-529','ceramic','سيراميك رخام مربع — للطلب','Marble-square ceramic — to order','#eee8e0'],
    ['CR-530','ceramic','سيراميك تيرازو فاتح — للطلب','Light terrazzo ceramic — to order','#e6e0d6'],
    ['CR-531','ceramic','سيراميك تيرازو رمادي — للطلب','Grey terrazzo ceramic — to order','#d0ccc6'],
    ['CR-532','ceramic','سيراميك كونكريت فاتح — للطلب','Light concrete ceramic — to order','#d5d3cf'],
    ['CR-533','ceramic','سيراميك كونكريت متوسط — للطلب','Medium concrete ceramic — to order','#b7b5b0'],
    ['CR-534','ceramic','سيراميك حجر رملي — للطلب','Sandstone ceramic — to order','#e0d0b4'],
    ['CR-535','ceramic','سيراميك حجر جيري — للطلب','Limestone ceramic — to order','#e8e0d2'],
    ['CR-536','ceramic','سيراميك زليج هادئ — للطلب','Quiet zellige look — to order','#d8efe6'],
    ['CR-537','ceramic','سيراميك أخضر زيتوني — للطلب','Olive ceramic — to order','#9aa48a'],
    ['CR-538','ceramic','سيراميك أزرق باهت — للطلب','Faded blue ceramic — to order','#c5d0d8'],
    ['CR-539','ceramic','سيراميك طوبي ناعم — للطلب','Soft brick ceramic — to order','#c48a6a'],
    ['CR-540','ceramic','سيراميك حمام أبيض — للطلب','White bath ceramic — to order','#f4f6f5'],
    ['CR-541','ceramic','سيراميك مطبخ رمادي — للطلب','Kitchen grey ceramic — to order','#cfd3d6'],
    ['CR-542','ceramic','سيراميك عيادة — للطلب','Clinic ceramic — to order','#eef1f0'],
    ['CR-543','ceramic','سيراميك كافيه — للطلب','Café ceramic — to order','#e2d2b8'],
    ['CR-544','ceramic','سيراميك مطعم — للطلب','Restaurant ceramic — to order','#d8c4a6'],
    ['CR-545','ceramic','سيراميك صالون — للطلب','Salon ceramic — to order','#f3e6dc'],
    ['CR-546','ceramic','سيراميك عمود — للطلب','Column ceramic look — to order','#e8e4de'],
    ['CR-547','ceramic','سيراميك سداسي أبيض — للطلب','White hex ceramic look — to order','#f6f5f2'],
    ['CR-548','ceramic','سيراميك سداسي رمادي — للطلب','Grey hex ceramic look — to order','#d0d3d6'],
    ['CR-549','ceramic','سيراميك فيش بون — للطلب','Herringbone ceramic — to order','#e4d8c8'],
    ['CR-550','ceramic','سيراميك سابواي كريمي — للطلب','Cream subway ceramic — to order','#f0e6d6'],
    ['CR-551','ceramic','سيراميك لامع أبيض — للطلب','Gloss white ceramic — to order','#fafaf8'],
    ['CR-552','ceramic','سيراميك مطفي بيج — للطلب','Matte beige ceramic — to order','#e4d6c4'],
    ['CR-553','ceramic','سيراميك ميكرو تيرازو — للطلب','Micro terrazzo ceramic — to order','#ddd6cc'],
    ['CR-554','ceramic','سيراميك حائط مميز — للطلب','Feature ceramic wall — to order','#d8c8b4'],
    ['CR-555','ceramic','سيراميك استقبال — للطلب','Reception ceramic — to order','#eee8e2'],
    ['WP-711','chipboard','WPC فلوت بلوط — للطلب','WPC fluted oak — to order','#c4a574'],
    ['WP-712','chipboard','WPC فلوت جوز — للطلب','WPC fluted walnut — to order','#6b4428'],
    ['WP-713','chipboard','WPC فلوت رمادي — للطلب','WPC fluted grey — to order','#8a8278'],
    ['WP-714','chipboard','WPC فلوت أبيض — للطلب','WPC fluted white — to order','#ece8e2'],
    ['WP-715','chipboard','WPC فلوت أسود — للطلب','WPC fluted black — to order','#2c2c2e'],
    ['WP-716','chipboard','WPC شيبورد فاتح — للطلب','WPC light chipboard — to order','#e0d4c2'],
    ['WP-717','chipboard','WPC شيبورد متوسط — للطلب','WPC medium chipboard — to order','#cbb892'],
    ['WP-718','chipboard','WPC شيبورد غامق — للطلب','WPC dark chipboard — to order','#8a7050'],
    ['WP-719','chipboard','WPC بامبو فاتح — للطلب','WPC light bamboo — to order','#e0cc9a'],
    ['WP-720','chipboard','WPC بامبو متوسط — للطلب','WPC medium bamboo — to order','#c4a46a'],
    ['WP-721','chipboard','WPC خشب زيتوني — للطلب','WPC olive wood — to order','#8a7a48'],
    ['WP-722','chipboard','WPC خشب رملي — للطلب','WPC sand wood — to order','#d8c4a2'],
    ['WP-723','chipboard','WPC خشب فحمي — للطلب','WPC charcoal wood — to order','#3a342e'],
    ['WP-724','chipboard','WPC لوح جداري فاتح — للطلب','WPC light wall board — to order','#e6ddd0'],
    ['WP-725','chipboard','WPC لوح جداري دافئ — للطلب','WPC warm wall board — to order','#d8c4a8'],
    ['WP-726','chipboard','WPC عمود فلوت — للطلب','WPC fluted column — to order','#b8955e'],
    ['WP-727','chipboard','WPC واجهة محل — للطلب','WPC shop front wall — to order','#c9b18a'],
    ['WP-728','chipboard','WPC مكتب خطي — للطلب','WPC linear office — to order','#a89888'],
    ['WP-729','chipboard','WPC كافيه دافئ — للطلب','WPC warm café — to order','#b8884a'],
    ['WP-730','chipboard','WPC فندق هادئ — للطلب','WPC quiet hotel — to order','#cbb89a'],
    ['WP-731','chipboard','WPC مول محايد — للطلب','WPC neutral mall — to order','#d5d0c8'],
    ['WP-732','chipboard','WPC عيادة ناعم — للطلب','WPC soft clinic — to order','#e4e0da'],
    ['WP-733','chipboard','WPC صالون — للطلب','WPC salon wall — to order','#e8d4c4'],
    ['WP-734','chipboard','WPC جيم — للطلب','WPC gym wall — to order','#6e7276'],
    ['WP-735','chipboard','WPC مطعم — للطلب','WPC restaurant wall — to order','#8a5a3a'],
    ['WP-736','chipboard','WPC مدرسة — للطلب','WPC school wall — to order','#d8d4cc'],
    ['WP-737','chipboard','WPC ريب ضيق — للطلب','WPC narrow rib — to order','#c4b39a'],
    ['WP-738','chipboard','WPC ريب عريض — للطلب','WPC wide rib — to order','#b89a6a'],
    ['WP-739','chipboard','WPC سلات رمادي — للطلب','WPC grey slat — to order','#9a958e'],
    ['WP-740','chipboard','WPC سلات عسلي — للطلب','WPC honey slat — to order','#c49a62'],
    ['WP-741','chipboard','WPC بديل شيبورد كريمي — للطلب','WPC cream chipboard alt — to order','#efe6d4'],
    ['WP-742','chipboard','WPC بديل شيبورد جوزي — للطلب','WPC walnut chipboard alt — to order','#6a4630'],
    ['WP-743','chipboard','WPC حائط تلفزيون — للطلب','WPC TV wall — to order','#5c4634'],
    ['WP-744','chipboard','WPC استقبال — للطلب','WPC reception wall — to order','#d8cbb8'],
    ['WP-745','chipboard','WPC ممر — للطلب','WPC corridor wall — to order','#cfc6ba'],
    ['CB-609','chipboard','شيبورد كريمي — للطلب','Cream chipboard — to order','#efe6d4'],
    ['CB-610','chipboard','شيبورد بيج — للطلب','Beige chipboard — to order','#e0d0b8'],
    ['CB-611','chipboard','شيبورد رمادي — للطلب','Grey chipboard — to order','#c8c4bc'],
    ['CB-612','chipboard','شيبورد أبيض — للطلب','White chipboard — to order','#f4f1ec'],
    ['CB-613','chipboard','شيبورد جوزي — للطلب','Walnut chipboard — to order','#6b4428'],
    ['CB-614','chipboard','شيبورد بلوط — للطلب','Oak chipboard — to order','#c4a574'],
    ['CB-615','chipboard','شيبورد فحمي — للطلب','Charcoal chipboard — to order','#4a4642'],
    ['CB-616','chipboard','شيبورد رملي — للطلب','Sand chipboard — to order','#d8c8ae'],
    ['CB-617','chipboard','شيبورد زيتوني — للطلب','Olive chipboard — to order','#9a9478'],
    ['CB-618','chipboard','شيبورد مربع فاتح — للطلب','Light chipboard square — to order','#e8e0d4'],
    ['CB-619','chipboard','شيبورد مربع خشب — للطلب','Wood chipboard square — to order','#b8955e'],
    ['CB-620','chipboard','شيبورد فلوت — للطلب','Fluted chipboard — to order','#cbb892'],
    ['CB-621','chipboard','شيبورد محل — للطلب','Shop chipboard — to order','#d0c4b0'],
    ['CB-622','chipboard','شيبورد مكتب — للطلب','Office chipboard — to order','#c8c2b8'],
    ['CB-623','chipboard','شيبورد مدرسة — للطلب','School chipboard — to order','#ddd6cc'],
    ['CB-624','chipboard','شيبورد عيادة — للطلب','Clinic chipboard — to order','#e8e4de'],
    ['CB-625','chipboard','شيبورد كافيه — للطلب','Café chipboard — to order','#c9b18a'],
    ['CB-626','chipboard','شيبورد مول — للطلب','Mall chipboard — to order','#d8d2ca'],
    ['CB-627','chipboard','شيبورد عمود — للطلب','Column chipboard — to order','#c4b8a4'],
    ['CB-628','chipboard','شيبورد حائط مميز — للطلب','Feature chipboard — to order','#b89a6e'],
  ];
  var have={}; for (var i=0;i<F.length;i++) have[F[i][0]]=1;
  for (var j=0;j<more.length;j++) if(!have[more[j][0]]) F.push(more[j]);
  if (typeof SH!=="undefined"){
    var shHave={}; for (var s=0;s<SH.length;s++) shHave[SH[s][0]]=1;
    var sheets=[
      ['SH-446','لوح رخام كشمير 5مم','Cashmere marble 5mm sheet','#e3d5c4'],
      ['SH-447','لوح رخام صحراوي 5مم','Desert marble 5mm sheet','#d8c3a0'],
      ['SH-448','لوح كالاكاتا كتاب 5مم','Bookmatch Calacatta 5mm sheet','#f3eee6'],
      ['SH-449','لوح نيرو مطفي 5مم','Matte nero 5mm sheet','#2a2a2c'],
      ['SH-450','لوح ترافرتين 5مم','Travertine 5mm sheet','#e0d2bc'],
      ['SH-451','لوح خشب عسلي 5مم','Honey wood 5mm sheet','#c49a62'],
      ['SH-452','لوح خشب مدخن 5مم','Smoked wood 5mm sheet','#8d7b68'],
      ['SH-453','لوح خشب أبيض 5مم','White wood 5mm sheet','#e8e2d8'],
      ['SH-454','لوح كتان طبيعي 5مم','Natural linen 5mm sheet','#e4d8c8'],
      ['SH-455','لوح كتان رمادي 5مم','Grey linen 5mm sheet','#c8c4bc'],
      ['SH-456','لوح ساده كريمي 5مم','Cream solid 5mm sheet','#f3eadc'],
      ['SH-457','لوح ساده فحمي 5مم','Charcoal solid 5mm sheet','#3e4044'],
      ['SH-458','لوح سيراميك مترو أبيض','White metro ceramic sheet','#f5f5f2'],
      ['SH-459','لوح سيراميك تيرازو','Terrazzo ceramic sheet','#e0d8cc'],
      ['SH-460','لوح سيراميك كونكريت','Concrete ceramic sheet','#c8c6c2'],
      ['SH-461','لوح سيراميك حجر جيري','Limestone ceramic sheet','#e8e0d2'],
      ['SH-462','لوح شيبورد كريمي 5مم','Cream chipboard 5mm sheet','#efe6d4'],
      ['SH-463','لوح شيبورد جوزي 5مم','Walnut chipboard 5mm sheet','#6b4428'],
      ['SH-464','لوح WPC فلوت رمادي','WPC grey fluted sheet','#8a8278'],
      ['SH-465','لوح WPC فلوت عسلي','WPC honey fluted sheet','#c49a62'],
      ['SH-466','بلاطة سيراميك سداسي','Hex ceramic square sheet','#f3f2ee'],
      ['SH-467','بلاطة سيراميك فيش بون','Herringbone ceramic sheet','#e4d8c8'],
      ['SH-468','بلاطة شيبورد مربعة بلس','Chipboard square plus','#d8ccb8'],
      ['SH-469','بلاطة رخام كبيرة بلس','Large marble square plus','#f0ebe3'],
      ['SH-470','لوح حمام رخام فاتح','Light bath marble sheet','#f5f2ec'],
      ['SH-471','لوح مطبخ رخام رمادي','Kitchen grey marble sheet','#c5c8cb'],
      ['SH-472','لوح محل خشب دافئ','Warm shop wood sheet','#b88848'],
      ['SH-473','لوح مول محايد','Neutral mall sheet','#e4e0da'],
      ['SH-474','لوح مكتب رمادي','Office grey sheet','#c5c8cb'],
      ['SH-475','لوح عيادة فاتح','Clinic light sheet','#f2f4f3'],
      ['SH-476','لوح فندق كتان','Hotel linen sheet','#ddd2c2'],
      ['SH-477','لوح كافيه خشب','Café wood sheet','#a67c52'],
      ['SH-478','لوح مطعم دافئ','Restaurant warm sheet','#8a5a3a'],
      ['SH-479','لوح صالون ناعم','Salon soft sheet','#f0e4d8'],
      ['SH-480','لوح جيم رمادي','Gym grey sheet','#8a8e92'],
      ['SH-481','لوح مدرسة هادئ','School quiet sheet','#e6e2dc'],
      ['SH-482','لوح عمود فلوت','Fluted column sheet','#c4a574'],
      ['SH-483','لوح استقبال أبيض','Reception white sheet','#f7f5f1'],
      ['SH-484','لوح حائط مميز خشب','Feature wood sheet','#8b6a4a'],
      ['SH-485','لوح حائط مميز رخام','Feature marble sheet','#e8e0d4'],
    ];
    for (var k=0;k<sheets.length;k++) if(!shHave[sheets[k][0]]) SH.push(sheets[k]);
  }
  if (typeof SP!=="undefined"){
    var spHave={}; for (var a=0;a<SP.length;a++) spHave[SP[a][0]]=1;
    var spaces=[
      ['SP41','محل تجاري','Retail shop','واجهة داخلية وثيم سريع يتكرر','Fast interior theme you can repeat'],
      ['SP42','بوتيك أزياء','Fashion boutique','حائط مميز خلف العرض','Feature wall behind the display'],
      ['SP43','مول / ممر تجاري','Mall corridor','أعمدة وحوائط ممرات بلون محايد','Neutral corridor walls and columns'],
      ['SP44','مكتب إداري مفتوح','Open office','قاعات وخلفيات اجتماعات','Rooms and meeting backdrops'],
      ['SP45','عيادة طبية','Medical clinic','سطح يتنضّف بسهولة ولون هادئ','Easy-wipe, calm colour'],
      ['SP46','فندق / لوبي','Hotel lobby','تكرار نفس الكود في الغرف والممرات','Same code repeated in rooms and corridors'],
      ['SP47','كافيه','Café','خشب دافئ أو كتان حول البار','Warm wood or linen around the bar'],
      ['SP48','مدرسة / حضانة','School / nursery','صيانة قليلة وحوائط ممرات','Low upkeep corridor walls'],
      ['SP49','مطعم','Restaurant','حائط مميز وظهر بار','Feature wall and bar back'],
      ['SP50','صالون تجميل','Beauty salon','خلفية مرايا وكراسي','Backdrop for mirrors and chairs'],
      ['SP51','جيم / نادي','Gym','حوائط جافة عالية الحركة','Dry high-traffic walls'],
      ['SP52','مطبخ','Kitchen','ظهر رخامي أو سيراميك لوك — مش بديل عزل','Marble or ceramic look back — not waterproofing'],
      ['SP53','حمام داخلي','Interior bathroom','رطوبة يومية فقط، مش عزل إنشائي','Daily moisture only, not tanking'],
      ['SP54','عمود ديكور','Feature column','لف العمود بشرائح أو لوح','Wrap the column in slats or sheet'],
      ['SP55','كاونتر استقبال','Reception desk wall','الحائط خلف الكاونتر','The wall behind the desk'],
      ['SP56','حائط مميز','Feature wall','تلفزيون أو لوحة أو شعار','TV, art, or a logo wall'],
      ['SP57','محل موبايلات','Phone shop','خلفية عرض محايدة','Neutral display backdrop'],
      ['SP58','صيدلية','Pharmacy','حوائط نظيفة فاتحة','Clean light walls'],
      ['SP59','معمل تحاليل','Lab reception','استقبال هادئ سهل المسح','Calm wipe-clean reception'],
      ['SP60','قاعة اجتماعات','Boardroom','حائط عرض خلف الشاشة','Display wall behind the screen'],
      ['SP61','غرفة فندقية','Hotel bedroom','هيدبورد وحائط جانبي','Headboard and side wall'],
      ['SP62','لوبي مول','Mall lobby','رخام لوك خفيف الوزن','Light-weight marble look'],
      ['SP63','كافيتريا مكتب','Office café corner','ركن دافئ داخل الشركة','A warm corner inside the office'],
      ['SP64','فصل دراسي','Classroom','حائط خلفي منخفض الصيانة','Low-maintenance back wall'],
      ['SP65','مطبخ مطعم','Restaurant kitchen pass','ظهر منطقة التسليم الداخلي','Interior pass-through back'],
      ['SP66','ركن حلاق','Barber corner','حائط خلف الكرسي','Wall behind the chair'],
      ['SP67','استوديو لياقة','Fitness studio','حائط مرايا جانبي جاف','Dry wall beside mirrors'],
      ['SP68','مطبخ شقة','Apartment kitchen','ظهر الرخام بين الخزائن','Backsplash between cabinets'],
      ['SP69','حمام أطفال','Kids bathroom','لون فاتح ومسح يومي','Light colour, daily wipe'],
      ['SP70','عمود مدخل','Entrance column','أول انطباع عند الباب','First impression at the door'],
      ['SP71','كاونتر فندق','Hotel desk wall','خلف مكتب الاستقبال','Behind the front desk'],
      ['SP72','حائط شعار الشركة','Company logo wall','سطح مستوٍ للشعار','A flat face for the logo'],
      ['SP73','محل حلويات','Pastry shop','خلفية فاتحة للعرض','Light display backdrop'],
      ['SP74','عيادة أسنان','Dental clinic','حوائط انتظار واستقبال','Waiting and reception walls'],
      ['SP75','مكتب محاماة','Law office','خشب هادئ وكتان','Quiet wood and linen'],
      ['SP76','مطعم كافيه مول','Mall café','وحدة داخل المول','A unit inside the mall'],
      ['SP77','غرفة مدرسين','Teachers room','حائط جانبي بسيط','A simple side wall'],
      ['SP78','بار مطعم','Restaurant bar','فلوت خشبي خلف البار','Wood flutes behind the bar'],
      ['SP79','صالون رجالي','Men salon','خشب داكن أو رمادي','Dark or grey wood'],
      ['SP80','جدار أجهزة الجيم','Gym equipment wall','رمادي صلب سهل المسح','Solid grey, easy wipe'],
    ];
    for (var b=0;b<spaces.length;b++) if(!spHave[spaces[b][0]]) SP.push(spaces[b]);
  }
  if (typeof PROJ!=="undefined"){
    var pjHave={}; for (var c=0;c<PROJ.length;c++) pjHave[PROJ[c][0]]=1;
    var projs=[
      ['PJ13','محل أزياء','Fashion shop','حائط عرض + عمود','display wall + column','فكرة استخدام'],
      ['PJ14','ممر مول','Mall corridor','ألواح محايدة','neutral sheets','فكرة استخدام'],
      ['PJ15','قاعة اجتماعات','Meeting room','خلفية شاشة','screen wall','فكرة استخدام'],
      ['PJ16','صالون','Salon','خلفية مرايا','mirror wall','فكرة استخدام'],
      ['PJ17','جيم','Gym','حائط جاف','dry wall','فكرة استخدام'],
      ['PJ18','مطبخ شقة','Apartment kitchen','ظهر 5مم','5mm back','فكرة استخدام'],
      ['PJ19','حمام داخلي','Interior bath','رخام لوك','marble look','فكرة استخدام'],
      ['PJ20','عمود مدخل','Entrance column','فلوت','fluted wrap','فكرة استخدام'],
      ['PJ21','كاونتر استقبال','Reception desk','حائط خلف الكاونتر','desk backdrop','فكرة استخدام'],
      ['PJ22','حائط تلفزيون','TV feature wall','خشب + رخام','wood + marble','فكرة استخدام'],
      ['PJ23','مدرسة','School corridor','صيانة قليلة','low upkeep','فكرة استخدام'],
      ['PJ24','مطعم','Restaurant feature','حائط مميز','feature wall','فكرة استخدام'],
    ];
    for (var d=0;d<projs.length;d++) if(!pjHave[projs[d][0]]) PROJ.push(projs[d]);
  }
  function sync(){
    var fc=String(F.length), sc=(typeof SH!=="undefined")?String(SH.length):"";
    if (typeof AR!=="undefined"){
      if (AR.stats){ AR.stats[1]=[fc,"كود تشطيب"]; if(sc) AR.stats[2]=[sc,"كود لوح"]; }
      AR.colS=fc+" كود تشطيب: خشب ورخام وسيراميك لوك وشيبورد/WPC وكتان وساده. اللي من غير صورة مكتوب عليه «للطلب». السعر عند الطلب فقط ولا يُنشر.";
      AR.shS=sc+" كود لوح/بلاطة · 5 مم · 1.22 × 2.80 م · حوالي 3.416 م² للوح. السعر عند الطلب.";
      AR.colNote="اللون على الشاشة تقريبي. الأكواد اللي عليها صورة كتالوج صورة حقيقية؛ الباقي «للطلب» من غير صورة ومن غير سعر. العيّنة من المصنع هي المرجع.";
    }
    if (typeof EN!=="undefined"){
      if (EN.stats){ EN.stats[1]=[fc,"Finish codes"]; if(sc) EN.stats[2]=[sc,"Sheet codes"]; }
      EN.colS=fc+" finish codes: wood, marble, ceramic look, chipboard/WPC, linen, solid. Codes without a photo are marked to order. Price is quoted only.";
      EN.shS=sc+" sheet/square codes · 5 mm · 1.22 × 2.80 m · about 3.416 m². Price on request.";
      EN.colNote="Screen colour is approximate. Codes with a catalog photo are real shots; the rest are to order, with no photo and no price. The factory sample is the reference.";
    }
  }
  sync();
})();
