const F=[
["M1-001","wood","خشب رمادي فاتح","Light grey wood","#b7aaa0","صالة ومكتب","Living / office"],
["M1-002","wood","خشب رمادي دافئ","Warm grey wood","#a89482","غرفة نوم","Bedroom"],
["M1-003","wood","خشب متوسط","Medium wood","#8b6a4a","كافيه","Café"],
["M1-004","wood","خشب كلاسيك","Classic wood","#6e4f35","فندق","Hotel"],
["M1-005","wood","خشب محمر","Red-tone wood","#7a4332","مطعم","Restaurant"],
["M1-006","wood","خشب غامق","Dark wood","#3f2d22","تلفزيون","TV wall"],
["M1-007","wood","خشب عقدي","Knotted wood","#5c4634","محل","Shop"],
["M1-008","wood","خشب زيتي","Olive wood","#6b6144","عيادة","Clinic"],
["M1-009","wood","خشب رملي","Sand wood","#c2ae8b","صالة","Living"],
["M1-010","wood","خشب بلوط فاتح","Light oak","#cbb892","مكتب","Office"],
["M1-011","wood","خشب بلوط عسلي","Honey oak","#b8894a","فندق","Hotel"],
["M1-012","wood","خشب جوزي متوسط","Mid walnut","#6b4a32","تلفزيون","TV wall"],
["M1-013","wood","خشب جوزي غامق","Dark walnut","#4a2f1f","استقبال","Reception"],
["M1-014","wood","خشب رمادي دخاني","Smoke grey wood","#7d7368","شركة","Corporate"],
["M1-015","wood","خشب أبيض مُعتّق","Aged white wood","#e4ddd2","عيادة","Clinic"],
["M1-016","wood","خشب كربوني","Carbon wood","#2c2622","محل","Shop"],
["M1-017","wood","خشب صنوبر دافئ","Warm pine","#d2b48c","غرفة أطفال","Kids room"],
["M1-018","wood","خشب تيك","Teak wood","#9a6b3f","كافيه","Café"],
["M1-019","wood","خشب رمادي بارد","Cool grey wood","#9a958c","مكتب","Office"],
["M1-020","wood","خشب كستنائي","Chestnut","#6e3f2a","مطعم","Restaurant"],
["M1-021","wood","خشب قشدي","Cream wood","#d9cbb0","صالة","Living"],
["M1-022","wood","خشب رمادي أزرق","Blue-grey wood","#7a8086","فندق","Hotel"],
["M1-023","wood","خشب بندقي","Hazelnut wood","#8a5a3c","محل","Shop"],
["M1-024","wood","خشب زيتوني غامق","Dark olive wood","#55503a","شركة","Corporate"],
["M1-025","wood","خشب طبيعي فاتح","Natural light wood","#c8ae7e","شقة","Apartment"],
["M2-001","textile","كتان / قماش","Linen / textile","#d7cfc3","غرفة نوم","Bedroom"],
["M2-002","textile","كتان رملي","Sand linen","#cfc0a8","صالة","Living"],
["M2-003","textile","كتان رمادي","Grey linen","#b8b3a9","مكتب","Office"],
["M2-004","textile","قماش بيج دافئ","Warm beige fabric","#d4c4a8","فندق","Hotel"],
["M2-005","textile","قماش فضي هادئ","Soft silver fabric","#c9c9d0","عيادة","Clinic"],
["M2-006","textile","كتان أخضر زيتوني","Olive linen","#a8a088","استقبال","Reception"],
["M2-007","textile","قماش كريمي","Cream fabric","#ebe3d4","غرفة نوم","Bedroom"],
["M2-008","textile","قماش رمادي دخاني","Smoke fabric","#8f8a84","شركة","Corporate"],
["M3-001","marble","رخام فاتح","Light marble","#ece7df","حمام","Bath"],
["M3-002","marble","رخام رمادي","Grey marble","#9aa0a6","مطبخ","Kitchen"],
["M3-003","marble","رخام معرّق","Veined marble","#d9d2c8","استقبال","Reception"],
["M3-004","marble","رخام كالكاتا","Calacatta marble","#f0ebe3","مطبخ","Kitchen"],
["M3-005","marble","رخام كارارا","Carrara marble","#e8e6e1","حمام","Bath"],
["M3-006","marble","رخام إمبراطوري بيج","Imperial beige","#d4c4ae","فندق","Hotel"],
["M3-007","marble","رخام رمادي غامق","Dark grey marble","#6a6e72","شركة","Corporate"],
["M3-008","marble","رخام أسود معرّق","Black veined marble","#3a3a3c","تلفزيون","TV wall"],
["M3-009","marble","رخام ترافرين","Travertine","#d8c9b0","مدخل","Entrance"],
["M3-010","marble","رخام بيج ناعم","Soft beige marble","#e2d5c2","صالة","Living"],
["M3-011","marble","رخام رمادي فاتح عرق","Light grey vein","#d0d3d6","مكتب","Office"],
["M3-012","marble","رخام أخضر هادئ","Soft green marble","#b8c0b0","عيادة","Clinic"],
["M3-013","marble","رخام ذهبي عرق","Gold vein marble","#e8d7b8","استقبال","Reception"],
["M3-014","marble","رخام أبيض ناصع","Bright white marble","#f5f3ef","حمام","Bath"]
];
