const EN={dir:"ltr",brand:"TuBaoBao Egypt",sub:"PVC wall finishes",lang:"عربي",
heroK:"TuBaoBao Egypt · 埃及兔宝宝",heroT:"Premium interior walls,<br/>from a factory you can trust.",
heroS:"PVC slats and 5 mm sheets in wood, marble, linen and leather looks. Hundreds of clear codes, and a real sample in your hands before any volume. Made in Egypt, supplied nationwide.",
cta1:"Browse finishes",cta2:"The factory",
heroFinishes:"Browse finishes",heroContact:"Contact",
heroCap:"Showroom still · application idea",
stats:[["~10,000 m²","Factory floor"],["144+","Finish codes"],["74+","Sheets / squares"],["Indoor","Use only"]],
aboutT:"About",aboutP:"TuBaoBao Egypt · 埃及兔宝宝 is an Egyptian factory dedicated to interior wall finishes. On a floor of about 10,000 m² we manufacture PVC wall slats and wood-look and marble-look sheets for apartments, shops, cafés, restaurants, offices, clinics, hotels and commercial fit-outs. Every finish carries a fixed code, you see the real sample before you confirm, and packing is separated by code so your supply arrives exactly as chosen. Interiors are our specialty, and we do them properly.",
prodT:"Product lines",prodS:"Three product families, all made in-house.",
lines:[["Fluted slats","Wall slats 280 cm long, 13.4–20 cm wide, with 5 mm foam backing.","#8b6a4a"],["Marble & ceramic look","122 × 280 sheets and squares for kitchens and reception.","#d9d2c8"],["Trims & system","Corners, end caps, start profiles and foam for a clean finish.","#c2a36b"]],
colT:"Finish library",colS:"Wide library: wood · marble · ceramic look · chipboard/WPC · linen · solid. Quoted by volume.",all:"All",wood:"Wood",textile:"Linen",marble:"Marble",ceramic:"Ceramic",chipboard:"Chipboard/WPC",solid:"Solid",leather:"Leather",
colNote:"Screen colour is approximate; catalog photos are factory samples.",
shT:"Large sheets",shS:"74+ sheet/square codes · 5 mm · 1.22 × 2.80 m · about 3.416 m² each.",
szT:"Sizes and profiles",szS:"Catalog widths 13.4 / 16 / 18 / 20 × 280 plus fluted / foam / trims.",
spT:"By space",spS:"A fast finish with clear codes.",
projT:"Projects & use sketches",projS:"Text sketches plus real factory/catalog photos in Gallery.",
spxT:"Specs",spxS:"Factory guide numbers.",
specH:["Item","Value"],spec:[["Material","PVC core + décor film"],["Slat length","280 cm standard"],["Catalog widths","13.4 / 16 / 18 / 20 cm"],["Helper foam","5 mm"],["Large sheet","122 × 280 × 5 mm"],["Sheet coverage","About 3.416 m²"],["Published use","Interior — daily moisture resistant"],["Price","On request by code and volume"],["Sample","From the factory before large confirmation"]],
profH:["Profile","W cm","H cm","L cm","Note"],
calcT:"Slat calculator",calcS:"Planning guide with about 8% waste.",lbW:"Wall width m",lbH:"Wall height m",lbSz:"Slat width",
calcNote:"Guide only — a survey reveals openings and real waste.",resA:"Area",resP:"Slats approx.",resS:"Sheet equivalent",
insT:"Install",insS:"Dry install on a flat wall or foam leveling layer.",
steps:[["Measure","Deduct openings + about 8% waste."],["Surface","Flat or 5 mm foam."],["Layout","Last slat not too thin."],["Fix","PVC adhesive or groove."],["Click","Tongue into groove."],["Cut","Fine-tooth saw."],["Trims","Corners and end caps."],["Clean","Water and soft cloth."]],
accT:"Trims",accS:"Corners, end caps, foam and helper profiles.",
cmpT:"PVC vs wood vs marble",cmpS:"Each material has a job.",
cmpH:["Topic","TuBaoBao PVC","Natural wood","Marble / stone"],
cmp:[["Wall weight","Light","Medium","Heavy"],["Install speed","Fast","Longer","Heavier / slower"],["Daily moisture","Good indoors","Swell-sensitive","Excellent as stone"],["Care","Periodic wipe","Paint / sand","Polish"],["Look stability","Stable factory print","Variable grain","Natural stone"],["Best fit","Fast décor & repeat codes","Joinery","Heavy stone"]],
faqT:"FAQ",faq:[],
ctT:"Talk to the factory",ctS:"Ask for a quote, a sample or a supply order. Tap Contact or message us on WhatsApp.",ctNote:"Use the Contact button in the menu, or the WhatsApp button. 08:00–20:00 except Friday.",
addr:"5th Industrial Zone — 6th of October City — Plot 37",hours:"08:00–20:00 · closed Friday",
foot:"TuBaoBao Egypt · 6th of October factory · Plot 37",
vizT:"See the wall before it is installed",vizLead:"Send a photo, the wall size and a code. We send back a look preview before install.",vizBtn:"Preview details",appIdeaLong:"Look preview",
videoStripT:"In motion",videoS:"Visual ideas of finishes in real rooms, not filmed jobs.",videoNote:"A visual application idea — not a filmed job",videoAll:"All videos",
chooserT:"How to choose",chooserLead:"Match the finish to the room: wood, marble, ceramic, linen or leather.",chooserBtn:"Open the chooser",
usesT:"Where it belongs",usesLead:"Ideas for where each finish fits best.",usesAll:"All places",appIdea:"Application idea",
searchT:"Search the library",searchLead:"Find a finish by code or name.",searchPh:"Search by code or finish name",searchBtn:"Search",
factoryHomeT:"Factory samples",factoryHomeLead:"Real catalog shots by code, and sheet samples exactly as they ship.",facCap:"Factory sample",
factsT:"At a glance",
contactPage:"Contact page",contactNote:"Tap Contact in the header or the WhatsApp button.",
rooms:{restaurant:"Restaurant",salon:"Salon",gym:"Gym",leatherbed:"Leather bedroom",reception:"Reception",living:"Living room",kitchen:"Kitchen",pharmacy:"Pharmacy",clinic:"Clinic corridor",lobby:"Hotel lobby",preview3d:"Wall preview",chooser:"Sample board"},
more:"More",waBtn:"Contact",waShort:"WhatsApp"};
