const F=[
["M1-001","wood","خشب رمادي فاتح","Light grey wood","#b7aaa0","صالة ومكتب","Living / office"],
["M1-002","wood","خشب رمادي دافئ","Warm grey wood","#a89482","غرفة نوم","Bedroom"],
["M1-003","wood","خشب متوسط","Medium wood","#8b6a4a","كافيه","Café"],
["M1-004","wood","خشب كلاسيك","Classic wood","#6e4f35","فندق","Hotel"],
["M1-005","wood","خشب محمر","Red-tone wood","#7a4332","مطعم","Restaurant"],
["M1-006","wood","خشب غامق","Dark wood","#3f2d22","تلفزيون","TV wall"],
["M1-007","wood","خشب عقدي","Knotted wood","#5c4634","محل","Shop"],
["M1-008","wood","خشب زيتي","Olive wood","#6b6144","عيادة","Clinic"],
["M1-009","wood","خشب رملي","Sand wood","#c2ae8b","صالة","Living"],
["M2-001","textile","كتان / قماش","Linen / textile","#d7cfc3","غرفة نوم","Bedroom"],
["M3-001","marble","رخام فاتح","Light marble","#ece7df","حمام","Bath"],
["M3-002","marble","رخام رمادي","Grey marble","#9aa0a6","مطبخ","Kitchen"],
["M3-003","marble","رخام معرّق","Veined marble","#d9d2c8","استقبال","Reception"]
];
const SH=[["500","رخام كريمي","Cream marble","#e8d9c4"],["502","رخام أبيض عرق","White grey vein","#f2f0ea"],["503","رخام بيج","Beige marble","#d8c3a2"],["504","رخام رمادي","Soft grey","#c5c8cb"],["505","رخام غامق","Dark marble","#5c5854"],["506","كالكاتا","Calacatta","#efeae2"],["J0407","خشب طبيعي","Natural wood","#8a6239"],["303","خشب رمادي","Grey wood","#8d8278"],["304","خشب جوزي","Walnut","#5a3b28"],["313","خشب فاتح","Light wood","#c9b48a"],["318","ساده دافئ","Warm solid","#d7c4a6"],["319","ساده بارد","Cool solid","#d9ddd8"],["530","رخام إمبراطوري","Imperial","#cfc3b0"]];
const PR=[["801","16","2.5","280","عريض مجوّف","Wide hollow"],["802","20","1.5","280","أعرض أنحف","Wider slim"],["803","13.5","1.6","280","أضيق","Narrow"],["804","15","2.2","280","متوسط","Medium"],["805","15.8","2.2","280","متوسط+","Medium+"]];
const SP=[["صالة","Living","تجاليد وتلفزيون","TV wall"],["غرفة نوم","Bedroom","هيدبورد","Headboard"],["مطبخ","Kitchen","ظهر رخامي","Backsplash"],["حمام","Bathroom","حائط داخلي رطب","Wet interior"],["مدخل","Entrance","انطباع أول","First look"],["محل","Retail","ثيم سريع","Fast theme"],["كافيه","Café","خشب دافئ","Warm wood"],["مكتب","Office","قاعات","Meeting rooms"],["عيادة","Clinic","سطح يتنظف","Wipe-clean"],["فندق","Hotel","أكواد موحّدة","Repeat codes"],["شركة","Corporate","استقبال","Reception"],["مسجد","Mosque","هدوء لوني","Calm walls"],["مدرسة","School","صيانة قليلة","Low upkeep"],["معرض","Showroom","عينة حية","Live sample"]];
const GOV=["القاهرة","الجيزة","6 أكتوبر","الإسكندرية","الساحل الشمالي","العاصمة الإدارية","التجمع","الشروق","بدر","العاشر","الإسماعيلية","السويس","بورسعيد","دمياط","المنصورة","طنطا","المنوفية","البحيرة","أسيوط","سوهاج","قنا","الأقصر","أسوان"];
const ACC=[["زاوية داخلية","Inner corner"],["زاوية خارجية","Outer corner"],["نهاية / غطاء حرف","End cap"],["فوم بورد 5 مم","5 mm foam board"],["لاصق PVC","PVC adhesive"],["قطاع بداية","Starter profile"]];
const PACK=[["حزم حسب القطاع","Bundles by profile"],["فصل الأكواد","Codes kept separate"],["حماية أركان","Corner protection"],["بطاقة كود على الحزمة","Code label on pack"],["تحميل من المصنع","Factory loading"],["تصدير بعد الاتفاق","Export after terms"]];
const TABS=[
["home","الرئيسية","Home"],["about","من نحن","About"],["products","المنتجات","Products"],["colors","الألوان","Finishes"],["sheets","الألواح","Sheets"],["sizes","المقاسات","Sizes"],["spaces","الاستخدامات","Spaces"],["specs","المواصفات","Specs"],["calc","الحاسبة","Calculator"],["install","التركيب","Install"],["access","الإكسسوار","Trims"],["compare","مقارنة","Compare"],["care","العناية","Care"],["trade","التجار","Trade"],["export","التصدير","Export"],["gov","المحافظات","Cities"],["pack","التعبئة","Packing"],["factory","المصنع","Factory"],["soon","قادم","Coming"],["faq","الأسئلة","FAQ"],["contact","تواصل","Contact"]
];
const AR={dir:"rtl",brand:"توباباو مصر",sub:"TuBaoBao Egypt · مصنع 6 أكتوبر",lang:"EN",
heroK:"مصنع · 6 أكتوبر · قطعة 37",heroT:"الشكل الفاخر.<br/>التركيب السريع.",
heroS:"شرائح تجاليد PVC 16 و18 و20 × 280 سم، وألواح بديل رخام وخشب 1.22 × 2.80 م بسمك 5 مم.",
cta1:"افتح المنتجات",cta2:"افتح المصنع",
stats:[["قطعة 37","المصنع"],["21","تبويب"],["16 / 18 / 20","عرض سم"],["داخلي","الاستخدامم"]],
aboutT:"من نحن",aboutP:"توباباو مصر مصنع ديكور في المنطقة الصناعية الخامسة بمدينة 6 أكتوبر، قطعة 37. نصنّع شرائح وألواح بديل خشب وبديل رخام للشقق والمحلات والكافيهات والمكاتب والعيادات والفنادق.",
prodT:"خطوط الإنتاج",prodS:"ثلاث عائلات واضحة. كل تبويب باب مستقل.",
lines:[["شرائح التجاليد","PVC مجوّف، طول 280 سم، مع فوم بورد 5 مم.","#8b6a4a"],["اللوح الكبير","122 × 280 سم × 5 مم للجدران الواسعة.","#d9d2c8"],["إكسسوار","زوايا ونهاية وفوم. أبواب WPC لاحقاً.","#c2a36b"]],
colT:"مكتبة الألوان",colS:"13 كود. السعر حسب الكمية ولا يُنشر.",all:"الكل",wood:"خشب",textile:"كتان",marble:"رخام",
colNote:"اللون على الشاشة تقريبي. العيّنة من المصنع هي المرجع.",
shT:"ألواح كبيرة",shS:"5 مم · 1.22 × 2.80 م · حوالي 3.416 م² للوح.",
szT:"المقاسات والقطاعات",szS:"العرض 16 و18 و20 سم. الطول القياسي 280 سم.",
spT:"حلول حسب المكان",spS:"تشطيب سريع مش مجرد خامة.",
spxT:"المواصفات",spxS:"أرقام المصنع.",
specH:["البند","القيمة"],spec:[["الخامة","PVC مجوّف + فيلم"],["الطول","280 سم"],["العرض","16 / 18 / 20 سم"],["الفوم","5 مم"],["اللوح","122 × 280 × 5 مم"],["التغطية","3.416 م²"],["الاستخدام","داخلي مقاوم للرطوبة"],["السعر","عند الطلب"]],
profH:["قطاع","عرض","ارتفاع","طول","ملاحظة"],
calcT:"حاسبة الشرائح",calcS:"استرشادي + هدر 8٪.",lbW:"عرض الحائط م",lbH:"ارتفاع الحائط م",lbSz:"عرض الشريحة",
calcNote:"لا يغني عن المعاينة.",resA:"المساحة",resP:"شرائح تقريباً",resS:"ألواح مكافئة",
insT:"التركيب",insS:"تركيب جاف فوق سطح مستو.",
steps:[["قياس","قِس وخصم الفتحات + 8٪."],["سطح","مستوي أو فوم 5 مم."],["توزيع","آخر شريحة متكونش رفيعة."],["تثبيت","لاصق PVC أو تعشيقة."],["تعشيق","لسان في مجرى."],["قص","منشار ناعم."],["إكسسوار","زاوية ونهاية."],["تنظيف","ماء وقماش."]],
accT:"الإكسسوار",accS:"الزاوية والنهاية والفوم جزء من النظام، مش إضافة شكلية.",
cmpT:"PVC مقابل الخشب والرخام",cmpS:"كل خامة لها وظيفة.",
cmpH:["البند","PVC","خشب","رخام"],
cmp:[["وزن","خفيف","متوسط","ثقيل"],["تركيب","سريع","أطول","ثقيل"],["مياه","مقاوم داخلياً","حساس","ممتاز"],["صيانة","مسح","دهان","جلي"],["شكل","نقشة ثابتة","عرق طبيعي","حجر"],["الأنسب","تجديد سريع","نجارة","أسطح حجر"]],
careT:"العناية",careS:"سطح داخلي. التنظيف بسيط لو اتركّب صح.",
care:[["امسح بقماش مبلل","ما تستخدمش سلك أو حجر."],["ابتعد عن المذيبات","تنر وأسيتون يبوّظ الفيلم."],["الحرارة المباشرة","موقد وسخان ملاصق مش مناسبين."],["الشمس الخارجية","الاستخدام المعلن داخلي."]],
trT:"للتجار",trS:"معارض ومقاولون ومصدرون.",
trade:[["سعر المصنع","بالطلب فقط."],["عينات","كود حقيقي قبل التعميد."],["توريد","من 6 أكتوبر لكل المحافظات."],["حد أدنى","مرن حسب الكود."],["دعم","قطاع وإكسسوار."],["فاتورة","حسب الاتفاق."]],
exT:"التصدير",exS:"تعبئة ومسار بعد الاتفاق. الرقم غير ظاهر حالياً.",
ex:[["ليبيا","مسار إقليمي معتاد."],["السودان","حسب التعبئة والمستندات."],["أسواق أخرى","بعد الاتفاق."],["التعبئة","حزم مفصولة بالكود."]],
govT:"التوريد داخل مصر",govS:"التحميل من المصنع في 6 أكتوبر.",
pkT:"التعبئة",pkS:"الكود يتكتب على الحزمة حتى لا تختلط التشطيبات.",
facT:"المصنع",facP:"المنطقة الصناعية الخامسة — 6 أكتوبر — قطعة 37. 8ص–8م عدا الجمعة.",
fac:[["الموقع","قطعة 37 · 6 أكتوبر"],["الإنتاج","شرائح وألواح داخلية"],["التغطية","مصر + تصدير إقليمي"]],
soonT:"قادم",soonS:"أبواب ليست معروضة للبيع الآن.",
soon:[["أبواب WPC","قيد الدراسة لخط لاحق."],["ألوان إضافية","حسب طلب التجار."],["صور كتالوج أكبر","هتتنزل دفعة صغيرة."]],
faqT:"أسئلة",
faq:[["الأسعار ظاهرة؟","لا. حسب الكود والكمية."],["كل المحافظات؟","نعم من 6 أكتوبر."],["تصدير؟","نعم بعد الاتفاق."],["الأكواد موجودة؟","أغلبها يُصنَّع."],["مقاس 18؟","نعم مع 16 و20."],["حمام؟","مقاوم رطوبة داخلية وليس عزل."],["شمس مباشرة؟","الاستخدام داخلي."],["عينة؟","من المصنع."],["أبواب؟","لاحقاً."],["رقم؟","سيُضاف لاحقاً."]],
ctT:"تواصل",ctS:"الرقم غير ظاهر حالياً.",ctNote:"وسيلة التواصل تُضاف لاحقاً حتى لا تنتشر أرقام قديمة.",
addr:"المنطقة الصناعية الخامسة — مدينة 6 أكتوبر — قطعة 37",hours:"8ص – 8م · عدا الجمعة",
foot:"توباباو مصر · مصنع 6 أكتوبر · قطعة 37"};
const EN={dir:"ltr",brand:"TuBaoBao Egypt",sub:"PVC factory · 6th of October",lang:"عربي",
heroK:"Factory · 6th of October · Plot 37",heroT:"The look of luxury.<br/>The speed of PVC.",
heroS:"PVC slats 16, 18 and 20 × 280 cm, plus 5 mm marble and wood-look sheets at 1.22 × 2.80 m.",
cta1:"Open products",cta2:"Open factory",
stats:[["Plot 37","Factory"],["21","Tabs"],["16 / 18 / 20","Width cm"],["Interior","Use"]],
aboutT:"About",aboutP:"TuBaoBao Egypt makes interior wood-look and marble-look PVC slats and sheets at Plot 37, 5th Industrial Zone, 6th of October City.",
prodT:"Product lines",prodS:"Three clear families. Each tab is its own door.",
lines:[["Fluted slats","Hollow PVC, 280 cm, with 5 mm foam board.","#8b6a4a"],["Large sheet","122 × 280 cm × 5 mm for wide walls.","#d9d2c8"],["Trims","Corners, end caps, foam. WPC doors later.","#c2a36b"]],
colT:"Finish library",colS:"13 codes. Price quoted, never listed.",all:"All",wood:"Wood",textile:"Linen",marble:"Marble",
colNote:"Screen colour is approximate. Factory sample is the reference.",
shT:"Large sheets",shS:"5 mm · 1.22 × 2.80 m · about 3.416 m² each.",
szT:"Sizes and profiles",szS:"Widths 16, 18 and 20 cm. Standard length 280 cm.",
spT:"By space",spS:"A fast finish, not only a material.",
spxT:"Specs",spxS:"Factory numbers.",
specH:["Item","Value"],spec:[["Material","Hollow PVC + film"],["Length","280 cm"],["Widths","16 / 18 / 20 cm"],["Foam","5 mm"],["Sheet","122 × 280 × 5 mm"],["Coverage","3.416 m²"],["Use","Interior moisture resistant"],["Price","On request"]],
profH:["Profile","W","H","L","Note"],
calcT:"Slat calculator",calcS:"Guide + 8% waste.",lbW:"Wall width m",lbH:"Wall height m",lbSz:"Slat width",
calcNote:"Does not replace a survey.",resA:"Area",resP:"Slats approx.",resS:"Sheet equivalent",
insT:"Install",insS:"Dry install on a flat wall.",
steps:[["Measure","Deduct openings + 8%."],["Surface","Flat or 5 mm foam."],["Layout","Last slat not too thin."],["Fix","PVC adhesive or groove."],["Click","Tongue into groove."],["Cut","Fine-tooth saw."],["Trims","Corner and end cap."],["Clean","Water and cloth."]],
accT:"Trims",accS:"Corners, end caps and foam are part of the system.",
cmpT:"PVC vs wood vs marble",cmpS:"Each material has a job.",
cmpH:["Topic","PVC","Wood","Marble"],
cmp:[["Weight","Light","Medium","Heavy"],["Install","Fast","Longer","Heavy"],["Water","Interior OK","Sensitive","Excellent"],["Care","Wipe","Paint","Polish"],["Look","Stable print","Natural grain","Stone"],["Best","Fast décor","Joinery","Stone tops"]],
careT:"Care",careS:"Interior surface. Easy if installed correctly.",
care:[["Damp cloth","No wire or stone pads."],["No solvents","Thinner and acetone damage the film."],["Heat","Do not park a stove against the panel."],["Sun","Published use is interior."]],
trT:"Trade",trS:"Showrooms, contractors, exporters.",
trade:[["Factory price","Quoted only."],["Samples","Real code first."],["Supply","Nationwide from October."],["MOQ","Flexible by code."],["Support","Profiles and trims."],["Invoice","As agreed."]],
exT:"Export",exS:"Packing and route after terms. Phone is empty for now.",
ex:[["Libya","Usual regional route."],["Sudan","After packing and papers."],["Other markets","By agreement."],["Packing","Bundles split by code."]],
govT:"Supply in Egypt",govS:"Loaded from the 6th of October factory.",
pkT:"Packing",pkS:"The code is marked on the bundle so finishes do not mix.",
facT:"Factory",facP:"5th Industrial Zone — 6th of October — Plot 37. 08:00–20:00 except Friday.",
fac:[["Site","Plot 37 · 6th of October"],["Output","Interior slats and sheets"],["Reach","Egypt + regional export"]],
soonT:"Coming",soonS:"Doors are not for sale yet.",
soon:[["WPC doors","Under study for a later line."],["More colours","On trade request."],["Larger catalogue photos","To be added in small batches."]],
faqT:"FAQ",
faq:[["Prices listed?","No. By code and volume."],["All governorates?","Yes from October."],["Export?","Yes after terms."],["Codes in stock?","Most are made here."],["18 cm?","Yes with 16 and 20."],["Bathroom?","Interior moisture, not tanking."],["Direct sun?","Interior use."],["Sample?","From the factory."],["Doors?","Later."],["Phone?","To be added later."]],
ctT:"Contact",ctS:"Phone is empty on purpose.",ctNote:"Contact details will be added later so old numbers do not spread.",
addr:"5th Industrial Zone — 6th of October City — Plot 37",hours:"08:00–20:00 · closed Friday",
foot:"TuBaoBao Egypt · 6th of October factory · Plot 37"};
