const EN={dir:"ltr",brand:"TuBaoBao Egypt",sub:"PVC factory · 6th of October",lang:"عربي",
heroK:"Factory · 6th of October · Plot 37",heroT:"The look of luxury.<br/>The speed of PVC.",
heroS:"PVC and WPC/chipboard cladding slats, plus marble-look, ceramic-look and wood-look sheets at 1.22 × 2.80 m. 6th of October factory · nationwide supply · approximate 3D design via WhatsApp.",
cta1:"Open products",cta2:"Open factory",
stats:[["~10,000 m²","Factory"],["144+","Finish codes"],["74+","Sheets / squares"],["Interior","Use"]],
aboutT:"About",aboutP:"TuBaoBao Egypt is an interior décor factory at Plot 37, 5th Industrial Zone, 6th of October City. We make PVC wall slats and wood-look / marble-look sheets for apartments, shops, cafés, restaurants, offices, clinics, hotels and commercial fit-outs. Factory footprint about 10,000 m².",
prodT:"Product lines",prodS:"Three clear families on the factory floor.",
lines:[["Fluted slats","Hollow PVC / WPC language, 280 cm, widths 13.4–20 cm with 5 mm foam.","#8b6a4a"],["Marble & ceramic look","122 × 280 sheets and squares for kitchens and reception.","#d9d2c8"],["Chipboard / system","Chipboard & WPC language + corners, end caps, foam. WPC doors later.","#c2a36b"]],
colT:"Finish library",colS:"Wide library: wood · marble · ceramic look · chipboard/WPC · linen · solid. Quoted by volume.",all:"All",wood:"Wood",textile:"Linen",marble:"Marble",ceramic:"Ceramic",chipboard:"Chipboard/WPC",solid:"Solid",
colNote:"Screen colour is approximate; catalog photos are factory samples.",
shT:"Large sheets",shS:"74+ sheet/square codes · 5 mm · 1.22 × 2.80 m · about 3.416 m² each.",
szT:"Sizes and profiles",szS:"Catalog widths 13.4 / 16 / 18 / 20 × 280 plus fluted / foam / trims.",
spT:"By space",spS:"A fast finish with clear codes.",
projT:"Projects & use sketches",projS:"Text sketches plus real factory/catalog photos in Gallery.",
spxT:"Specs",spxS:"Factory guide numbers.",
specH:["Item","Value"],spec:[["Material","Hollow PVC + décor film"],["Slat length","280 cm standard"],["Catalog widths","13.4 / 16 / 18 / 20 cm"],["Helper foam","5 mm"],["Large sheet","122 × 280 × 5 mm"],["Sheet coverage","About 3.416 m²"],["Published use","Interior — daily moisture resistant"],["Price","On request by code and volume"],["Sample","From the factory before large confirmation"]],
profH:["Profile","W cm","H cm","L cm","Note"],
calcT:"Slat calculator",calcS:"Planning guide with about 8% waste.",lbW:"Wall width m",lbH:"Wall height m",lbSz:"Slat width",
calcNote:"Guide only — a survey reveals openings and real waste.",resA:"Area",resP:"Slats approx.",resS:"Sheet equivalent",
insT:"Install",insS:"Dry install on a flat wall or foam leveling layer.",
steps:[["Measure","Deduct openings + about 8% waste."],["Surface","Flat or 5 mm foam."],["Layout","Last slat not too thin."],["Fix","PVC adhesive or groove."],["Click","Tongue into groove."],["Cut","Fine-tooth saw."],["Trims","Corners and end caps."],["Clean","Water and soft cloth."]],
accT:"Trims",accS:"Corners, end caps, foam and helper profiles.",
cmpT:"PVC vs wood vs marble",cmpS:"Each material has a job.",
cmpH:["Topic","TuBaoBao PVC","Natural wood","Marble / stone"],
cmp:[["Wall weight","Light","Medium","Heavy"],["Install speed","Fast","Longer","Heavier / slower"],["Daily moisture","Good indoors","Swell-sensitive","Excellent as stone"],["Care","Periodic wipe","Paint / sand","Polish"],["Look stability","Stable factory print","Variable grain","Natural stone"],["Best fit","Fast décor & repeat codes","Joinery","Heavy stone"]],
faqT:"FAQ",faq:[],
ctT:"Contact",ctS:"For a quote, sample or supply — WhatsApp.",ctNote:"Official contact: WhatsApp 01116208881 · 08:00–20:00 except Friday.",
addr:"5th Industrial Zone — 6th of October City — Plot 37",hours:"08:00–20:00 · closed Friday",
foot:"TuBaoBao Egypt · 6th of October factory · Plot 37",
more:"More",waBtn:"WhatsApp 01116208881",waShort:"WhatsApp"};
