const EN={dir:"ltr",brand:"TuBaoBao Egypt",sub:"PVC factory · 6th of October",lang:"عربي",
heroK:"Factory · 6th of October · Plot 37",heroT:"The look of luxury.<br/>The speed of PVC.",
heroS:"PVC wall slats in multiple widths × 280 cm, plus 5 mm marble and wood-look sheets at 1.22 × 2.80 m. A wide finish library across wood, linen and marble — loaded from the factory floor for supply across Egypt.",
cta1:"Open products",cta2:"Open factory",
stats:[["~10,000 m²","Factory"],["47","Finish codes"],["29","Sheet codes"],["Interior","Use"]],
aboutT:"About",aboutP:"TuBaoBao Egypt is an interior décor factory at Plot 37, 5th Industrial Zone, 6th of October City. We make PVC wall slats and wood-look / marble-look sheets for apartments, shops, cafés, restaurants, offices, clinics, hotels and commercial fit-outs. Factory footprint about 10,000 m² in the 6th of October industrial zone. Clear codes, real samples before large confirmation, and packing split by finish so consignments stay organised.",
prodT:"Product lines",prodS:"Three clear families on the factory floor. Each site tab is its own door into the details.",
lines:[["Fluted slats","Hollow PVC, 280 cm length, multiple widths (13.4 / 16 / 18 / 20 cm), with 5 mm foam board and corner/end trims.","#8b6a4a"],["Large sheet","122 × 280 cm × 5 mm for wide walls, kitchen backs and reception.","#d9d2c8"],["Trims & system","Corners, end caps, foam, starter and joiner profiles. WPC doors under study for a later line.","#c2a36b"]],
colT:"Finish library",colS:"47 finish codes across wood, linen and marble families. Price is quoted by volume — never listed here.",all:"All",wood:"Wood",textile:"Linen",marble:"Marble",
colNote:"Screen colour is approximate; catalog photos are factory samples. Physical sample remains the reference before large supply.",
shT:"Large sheets",shS:"29 sheet codes · 5 mm · 1.22 × 2.80 m · about 3.416 m² each.",
szT:"Sizes and profiles",szS:"Catalog widths include 13.4 cm and 20 cm flutes, plus common 16 / 18 / 20 cm profiles. Standard length 280 cm; some marble sheets shown near 290–300 cm.",
spT:"By space",spS:"A fast finish with clear codes — not only a material without context.",
projT:"Projects & use sketches",projS:"Text-only planning sketches plus real factory/catalog photos in Gallery. Codes and sizes adjust after a site survey.",
spxT:"Specs",spxS:"Factory guide numbers. Confirm finer detail when you request a quote.",
specH:["Item","Value"],spec:[["Material","Hollow PVC + décor film"],["Slat length","280 cm standard"],["Catalog widths","13.4 / 16 / 18 / 20 cm (+ other profiles)"],["Helper foam","5 mm paired with panels"],["Large sheet","122 × 280 × 5 mm"],["Sheet coverage","About 3.416 m²"],["Published use","Interior — daily moisture resistant"],["External sun","Not published as permanent outdoor use"],["Price","On request by code and volume"],["Sample","From the factory before large confirmation"]],
profH:["Profile","W cm","H cm","L cm","Note"],
calcT:"Slat calculator",calcS:"Planning guide with about 8% waste. Does not replace a site measure.",lbW:"Wall width m",lbH:"Wall height m",lbSz:"Slat width",
calcNote:"Guide only — a survey reveals openings, corners and real waste.",resA:"Area",resP:"Slats approx.",resS:"Sheet equivalent",
insT:"Install",insS:"Dry install on a flat wall or foam leveling layer. Good sequencing cuts waste and visual defects.",
steps:[["Measure","Measure the wall, deduct openings, then add about 8% waste."],["Surface","Flat substrate or 5 mm foam for light leveling."],["Layout","Distribute width so the last slat is not too thin."],["Fix","Suitable PVC adhesive or groove system by profile."],["Click","Tongue into groove with even pressure along the row."],["Cut","Fine-tooth saw; respect grain/print direction."],["Trims","Inner/outer corners and end caps where edges show."],["Clean","Lukewarm water and a soft cloth after dust settles."]],
accT:"Trims",accS:"Corners, end caps, foam and helper profiles are part of the install system — not only decoration.",
cmpT:"PVC vs wood vs marble",cmpS:"Each material has a job. Table is for practical interior fit-out comparison.",
cmpH:["Topic","TuBaoBao PVC","Natural wood","Marble / stone"],
cmp:[["Wall weight","Light","Medium","Heavy"],["Install speed","Fast","Longer","Heavier / slower"],["Daily moisture","Good indoors","Swell-sensitive","Excellent as stone"],["Care","Periodic wipe","Paint / sand at times","Polish and care"],["Look stability","Stable factory print","Variable natural grain","Natural stone"],["Best fit","Fast décor & repeat codes","Joinery detail","Heavy stone surfaces"]],
faqT:"FAQ",
faq:[],
ctT:"Contact",ctS:"For a quote, sample or supply order — message us on WhatsApp.",ctNote:"Official contact: WhatsApp 01116208881 · 08:00–20:00 except Friday.",
addr:"5th Industrial Zone — 6th of October City — Plot 37",hours:"08:00–20:00 · closed Friday",
foot:"TuBaoBao Egypt · 6th of October factory · Plot 37",
more:"More",waBtn:"WhatsApp 01116208881",waShort:"WhatsApp"};
