const SP=[
['SP01','تلفزيون حائط','TV wall feature','سكني','Residential'],
['SP02','مدخل فيلا','Villa entrance','سكني','Residential'],
['SP03','غرفة نوم رئيسية','Master bedroom','سكني','Residential'],
['SP04','مكتب منزلي','Home office','سكني','Residential'],
['SP05','مطبخ مفتوح','Open kitchen','سكني','Residential'],
['SP06','حمام داخلي','Interior bathroom','سكني','Residential'],
['SP07','ممر شقة','Apartment corridor','سكني','Residential'],
['SP08','شرفة مغلقة','Enclosed balcony','سكني','Residential'],
['SP09','غرفة أطفال','Kids room','سكني','Residential'],
['SP10','صالة معيشة','Living lounge','سكني','Residential'],
['SP11','لوبي فندق','Hotel lobby','تجاري','Commercial'],
['SP12','غرفة فندقية','Hotel room','تجاري','Commercial'],
['SP13','مطعم','Restaurant','تجاري','Commercial'],
['SP14','كافيه','Café','تجاري','Commercial'],
['SP15','عيادة','Clinic','تجاري','Commercial'],
['SP16','مكتب إداري','Office suite','تجاري','Commercial'],
['SP17','معرض تجاري','Showroom','تجاري','Commercial'],
['SP18','محل تجزئة','Retail shop','تجاري','Commercial'],
['SP19','جيم / نادي','Gym / club','تجاري','Commercial'],
['SP20','مسجد / مصلى','Prayer space','تجاري','Commercial'],
['SP21','مدرسة / حضانة','School / nursery','تجاري','Commercial'],
['SP22','عيادة أسنان','Dental clinic','تجاري','Commercial'],
['SP23','صالون تجميل','Beauty salon','تجاري','Commercial'],
['SP24','استوديو تصوير','Photo studio','تجاري','Commercial'],
['SP25','قاعة اجتماعات','Meeting room','تجاري','Commercial'],
['SP26','استقبال شركة','Corporate reception','تجاري','Commercial'],
['SP27','شقة فندقية','Serviced apartment','تجاري','Commercial'],
['SP28','فيلا ساحلية','Coastal villa','سكني','Residential'],
['SP29','دوبلكس','Duplex home','سكني','Residential'],
['SP30','بنتهاوس','Penthouse','سكني','Residential'],
['SP31','وحدة إدارية','Admin unit','تجاري','Commercial'],
['SP32','مركز طبي','Medical center','تجاري','Commercial'],
['SP33','مكتبة / ركن قراءة','Reading corner','سكني','Residential'],
['SP34','غرفة غسيل','Laundry room','سكني','Residential'],
['SP35','درج داخلي','Interior stair wall','سكني','Residential'],
['SP36','سقف معلق ديكور','Feature ceiling band','تجاري','Commercial'],
['SP37','عمود ديكور','Column wrap','تجاري','Commercial'],
['SP38','خلفية مرحلة','Stage backdrop','تجاري','Commercial'],
['SP39','منطقة انتظار','Waiting area','تجاري','Commercial'],
['SP40','مطبخ تجاري صغير','Small commercial kitchen area','تجاري','Commercial'],
];
const GOV=[
['G01','القاهرة','Cairo','القاهرة الكبرى','Greater Cairo'],
['G02','الجيزة','Giza','القاهرة الكبرى','Greater Cairo'],
['G03','القليوبية','Qalyubia','القاهرة الكبرى','Greater Cairo'],
['G04','6 أكتوبر','6th of October','مدن جديدة','New cities'],
['G05','الشيخ زايد','Sheikh Zayed','مدن جديدة','New cities'],
['G06','العاصمة الإدارية','New Administrative Capital','مدن جديدة','New cities'],
['G07','الشروق','El Shorouk','مدن جديدة','New cities'],
['G08','بدر','Badr','مدن جديدة','New cities'],
['G09','العبور','Obour','مدن جديدة','New cities'],
['G10','العاشر من رمضان','10th of Ramadan','مدن جديدة','New cities'],
['G11','الإسكندرية','Alexandria','الساحل','Coast'],
['G12','مطروح','Matrouh','الساحل','Coast'],
['G13','بورسعيد','Port Said','الساحل','Coast'],
['G14','السويس','Suez','الساحل','Coast'],
['G15','الإسماعيلية','Ismailia','القناة','Canal'],
['G16','دمياط','Damietta','الدلتا','Delta'],
['G17','الدقهلية','Dakahlia','الدلتا','Delta'],
['G18','الشرقية','Sharqia','الدلتا','Delta'],
['G19','الغربية','Gharbia','الدلتا','Delta'],
['G20','المنوفية','Monufia','الدلتا','Delta'],
['G21','كفر الشيخ','Kafr El Sheikh','الدلتا','Delta'],
['G22','البحيرة','Beheira','الدلتا','Delta'],
['G23','بني سويف','Beni Suef','الصعيد','Upper Egypt'],
['G24','الفيوم','Fayoum','الصعيد','Upper Egypt'],
['G25','المنيا','Minya','الصعيد','Upper Egypt'],
['G26','أسيوط','Assiut','الصعيد','Upper Egypt'],
['G27','سوهاج','Sohag','الصعيد','Upper Egypt'],
['G28','قنا','Qena','الصعيد','Upper Egypt'],
['G29','الأقصر','Luxor','الصعيد','Upper Egypt'],
['G30','أسوان','Aswan','الصعيد','Upper Egypt'],
['G31','البحر الأحمر','Red Sea','الساحل','Coast'],
['G32','جنوب سيناء','South Sinai','الساحل','Coast'],
['G33','شمال سيناء','North Sinai','الساحل','Coast'],
['G34','الوادي الجديد','New Valley','الصعيد','Upper Egypt'],
['G35','المنصورة الجديدة','New Mansoura','مدن جديدة','New cities'],
['G36','العلمين الجديدة','New Alamein','مدن جديدة','New cities'],
];
