const ACC=[
['A01','زاوية خارجية','External corner','PVC','trim'],
['A02','زاوية داخلية','Internal corner','PVC','trim'],
['A03','نهاية مستقيمة','End cap / skirting trim','PVC','trim'],
['A04','غطاء وصلة','Joint cover','PVC','trim'],
['A05','فوم تسوية 5مم','5mm leveling foam','foam','underlay'],
['A06','فوم تسوية 8مم','8mm leveling foam','foam','underlay'],
['A07','مسامير/مشابك','Clips / fasteners','steel','fixings'],
['A08','لاصق تركيب','Install adhesive','chem','adhesive'],
['A09','شريط إخفاء','Masking / finish tape','tape','finish'],
['A10','زاوية ديكور فلوت','Fluted décor corner','PVC','trim'],
['A11','نهاية فلوت','Fluted end trim','PVC','trim'],
['A12','قاعدة أرضية','Floor base trim','PVC','trim'],
['A13','غطاء مأخذ','Socket cover plate helper','PVC','accessory'],
['A14','زاوية عمود','Column corner set','PVC','trim'],
['A15','طقم بداية/نهاية','Start/end kit','PVC','kit'],
['A16','فوم لاصق خلفي','Adhesive foam backing','foam','underlay'],
['A17','قطاع WPC داخلي','Interior WPC profile language','WPC','profile'],
['A18','مشبك مخفي','Hidden clip','steel','fixings'],
['A19','حشوة فجوة','Gap filler strip','PVC','trim'],
['A20','حافظة زاوية معدنية','Metal corner protector','steel','protect'],
];
const PACK=[
['P01','حزمة حسب الكود','Bundle marked by code','يمنع خلط التشطيبات','stops finish mix-ups'],
['P02','حماية زوايا','Corner protectors','للنقل','for transport'],
['P03','تغليف ستريتش','Stretch wrap','ربط الحزم','bundle wrap'],
['P04','كرتون مقوّى','Reinforced carton','للعينات','for samples'],
['P05','قائمة تعبئة','Packing list','أكواد وكميات','codes & qty'],
['P06','فصل الألوان','Colour segregation','حزم منفصلة','separate bundles'],
['P07','تعبئة تصدير','Export packing','حماية إضافية','extra protection'],
['P08','علامات رطوبة','Moisture marks','إرشاد تخزين','storage guidance'],
['P09','تحذير تداول','Handling marks','لا ترمي الحزم','no dumping bundles'],
['P10','ترقيم دفعات','Batch numbering','إعادة الطلب','re-order ease'],
['P11','طبقة فوم بين الألواح','Foam interlayer','للألواح الكبيرة','for large sheets'],
['P12','حزام ربط','Strapping','ثبات الحزمة','bundle stability'],
['P13','كيس عينات','Sample pouch','كود واحد','single code'],
['P14','ملصق تعريف الحزمة','Bundle id label','كود التشطيب','finish code'],
['P15','تعبئة ليبيا/سودان','Libya/Sudan pack','مسار إقليمي','regional route'],
];
const PROJ=[
['PJ01','حائط تلفزيون فيلا','Villa TV wall','خشب + رخام','wood + marble','سكني'],
['PJ02','مدخل كمبوند','Compound entrance','رخام كالكاتا','Calacatta look','سكني'],
['PJ03','لوبي عيادات','Clinic lobby','ساده + كتان','solid + linen','تجاري'],
['PJ04','غرفة فندقية ساحل','Coastal hotel room','خشب فاتح','light wood','تجاري'],
['PJ05','مكتب إداري مدينة جديدة','New-city office','رمادي دخاني','smoke grey','تجاري'],
['PJ06','مطبخ مفتوح شقة','Apartment open kitchen','ساده كريمي','cream solid','سكني'],
['PJ07','عمود ديكور مول','Mall column wrap','فلوت رمادي','grey fluted','تجاري'],
['PJ08','خلفية كافيه','Café feature wall','كتان + خشب','linen + wood','تجاري'],
['PJ09','حمام داخلي دوبلكس','Duplex bath wall','رخام رمادي','grey marble','سكني'],
['PJ10','استقبال شركة','Corporate reception','نيرو + عاجي','nero + ivory','تجاري'],
['PJ11','ممر فندق','Hotel corridor','خشب عسلي','honey wood','تجاري'],
['PJ12','غرفة أطفال','Kids room wall','ساده فاتح','light solid','سكني'],
];
const TABS=[
['home','الرئيسية','Home'],
['products','المنتجات','Products'],
['colors','التشطيبات','Finishes'],
['sheets','الألواح','Sheets'],
['sizes','المقاسات','Sizes'],
['spaces','الاستخدامات','Spaces'],
['trade','التجار','Trade'],
['export','التصدير','Export'],
['factory','المصنع','Factory'],
['pack','التعبئة','Packing'],
['gov','التوريد','Supply'],
['faq','أسئلة','FAQ'],
['care','العناية','Care'],
['projects','مشاريع','Projects'],
['gallery','المعرض','Gallery'],
['soon','قريباً','Soon'],
['contact','تواصل','Contact'],
['about','عنّا','About'],
];
